name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Show the currently detailed version of Xcode for CLI
      run: xcode-select -p
      
    - name: Swift Lint
      uses: norio-nomura/action-swiftlint@3.2.0
      
    - name: Build
      run: swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator" -v

    - name: Run tests
      run: swift test -v
