name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.0,name=iPhone 8']

    steps:
    - uses: actions/checkout@v2
    - name: lint
      run: swift format lint --configuration .swift-format-config -r .
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
